# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160128_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.AccountSystem'),
        ),
    ]
